PB_UTIL.base_poker_hands = {
  "Straight Flush",
  "Four of a Kind",
  "Full House",
  "Flush",
  "Straight",
  "Three of a Kind",
  "Two Pair",
  "Pair",
  "High Card"
}

PB_UTIL.base_ranks = {
  "Ace",
  "King",
  "Queen",
  "Jack",
  "10",
  "9",
  "8",
  "7",
  "6",
  "5",
  "4",
  "3",
  "2"
}

PB_UTIL.base_rarities = {
  "Common",
  "Uncommon",
  "Rare",
  "Legendary"
}

PB_UTIL.base_suits = {
  "Spades",
  "Hearts",
  "Clubs",
  "Diamonds"
}

PB_UTIL.vanilla_food = {
  j_gros_michel = true,
  j_egg = true,
  j_ice_cream = true,
  j_cavendish = true,
  j_turtle_bean = true,
  j_diet_cola = true,
  j_popcorn = true,
  j_ramen = true,
  j_selzer = true,
}

-- Disable specific items by commenting them out
PB_UTIL.ENABLED_JOKERS = {
  "calling_card",
  "forgery",
  "wish_you_were_here",
  "quick_fix",
  "sacrificial_lamb",
  "the_one_who_waits",
  "unholy_alliance",
  "stamp",
  "solar_system",
  "pool_table",
  -- "moai",
  "meeple",
  "solemn_lament",
  "boundary_of_death",
  "furioso",
  "mismatched_sock",
  "wild_plus_four",
  "basic_energy",
  "punch_card",
  "jestrogen",
  "jestosterone",
  "reference_card",
  "oracle",
  "skydiver",
  "surfer",
  "apple",
  "freezer",
  "joker_cookie",
  "double_dutchman",
  "nachos",
  "crispy_taco",
  "soft_taco",
  "watermelon",
  "complete_breakfast",
  "ghost_cola",
  "b_soda",
  "marble_soda",
  "vacation_juice",
  "black_forest_cake",
  "ice_cube",
  "cream_liqueur",
  "deviled_egg",
  "chocolate_coins",
  "golden_apple",
  "champagne",
  "coffee",
  "matcha",
  "pinot_noir",
  "milk_tea",
  "epic_sauce",
  "dreamsicle",
  "popsicle_stick",
  "cakepop",
  "pop_stick",
  "caramel_apple",
  "pointy_stick",
  "charred_marshmallow",
  "sticky_stick",
  'aperol',
  'grenadine',
  'blue_curacao',
  'stout',
  "pear",
  "teapot",
  "sake_cup",
  "full_moon",
  "black_rainbows",
  "emergency_broadcast",
  "blue_marble",
  "triple_moon_goddess",
  "as_above_so_below",
  "one_sin_and_hundreds_of_good_deeds",
  "plague_doctor",
  "white_night",
  "angel_investor",
  "der_freischutz",
  "card_sleeve",
  "plastic_wrap",
  "shopping_center",
  "everything_must_go",
  "tutor",
  "percussion_ensemble",
  "its_tv_time",
  "trust_us",
  "eyelander",
  "cast_iron",
  "torii",
  "freight",
  "high_speed_rail",
  "small_scale_onshore_wind",
  "satellite_array",
  "first_contact",
  "aurora_borealis",
  "grand_strategy",
  "moving_out",
  "ready_to_fly",
  "great_wave",
  'one_shift_more',
  "let_it_happen",
  "paralyzed",
  "in_case_i_make_it",
  "rosary_beads",
  "joker_cd_i",
  "determination",
  "prince_of_darkness",
  "giga_size",
  "photocopy",
  "mandela_effect",
  "jester_of_nihil",
  "shopkeep",
  "wild_prize",
  "deadringer",
  "penumbra_phantasm",
  "a_balatro_movie",
  "ncj",
  "bicycle",
  -- "mezzetino",
  "gauze",
  "joke_master",
  "jokers_11",
  "book_of_life",
  "hamsa",
  "hamsa_r",
  "nazar",
  "oujia_board",
  "planchette",
  "prescript",
  "trans_flag",
  "pride_flag",
  "bismuth",
  "cherry_blossoms",
  "hole_in_one",
  "blue_bonnets",
  "derecho",
  "autumn_leaves",
  "river",
  "evergreens",
  "56_leaf_clover",
  "master_plan",
  "the_wonder_of_you",
  "tian_tian",
  "backpack",
  "roulette",
  "57_leaf_clover",
  "mexican_train",
  "coin_collection",
  "chocolate_joker",
  "tropic_birds",
  "attacking_vertical",
  "resurrections",
  "summoning_circle",
  "the_sun",
  "union_card",
  "book_of_vengeance",
  "moribund",
  "subterfuge",
  "the_world",
  "red_sun_in_the_sky",
  "jacks",
  "the_sun_rises",
  "blood_rain",
  -- "war_without_reason",
  "paranoia",
  "der_fluschutze",
  "touch_tone_joker",
  "the_batter",
  "off_switch",
  "off_alpha",
  "off_omega",
  "off_epsilon",
  "jestrica",
  "you_are_a_fool",
  "alert",
  "legacy",
  -- "redscreen",
  "telamon",
  "emf_reader",
  -- "squall_line",
  "weather_radio",
  "power_surge",
  "time_regression_mix",
  "find_jimbo",
  "joker_crossing",
  "jester",
  -- "tower_of_balatro",
  "jimbos_inferno",
  "tome",
  "journal",
  "park_postcard",
  "keycard",
  "greeting_card",
  -- "an_invitation",
  "jimbocards",
  "forlorn",
  "protocol",
  "showdown",
  "guns_blazin",
  "burning_pact",
  "blade_dance",
  "claw",
  "inner_peace",
  "jimbos_joyous_joker_jamboree",
  "banana_man",
  "mind_electric",
  "the_normal_joker",
  "ampersand",
  "shuttle",
  "silent_assassin",
  "insurance_policy",
  "disco",
  "unionized_labor",
  "better_call_jimbo",
  "jimbo_adventure",
  "ddakji",
  "yacht_dice",
  "deck_of_cards",
  "pocket_pair",
  "ultra_rare",
  -- "lore_digger",
  "the_quiet",
  "big_misser",
  -- "sinister_minds",
  "stereoscopic_specs",
  "fodder",
  "the_strongest",
  "da_capo",
  "golden_egg",
  "heretical_joker",
  "quartz",
  "rock_candy",
  "rockin_stick",
  "nigori",
  "birches",
  "black_star",
  "shooting_star",
  "stella_octangula",
  "blue_star",
  "shadowmantle",
  "zealous_joker",
  "lurid_joker",
  "the_dynasty",
  "j_and_js",
  "master_spark",
  "yacht",
  "prism",
  "fraudulent_joker",
  "pyrite",
  "tanghulu",
  "sweet_stick",
  "lager",
  "wheat_field",
  "solar_eclipse",
  "gambit",
  "king_me",
  "loaded_dice",
  -- "regicide",
  -- "bergentrucking"
  "towering_pillar_of_hats",
  "manilla_folder",
  "joker_duty",
  "clippy",
  "chip_clip",
  "clothespin",
  "kintsugi_joker",
  "happy_accident",
  "watercolor_joker",
  "medic",
  "festive_joker",
  "sommelier",
  "spotty_joker",
  "collector",
  "langely",
  "pedrillo",
  "nichola",
  "chaplin",
  -- "shinzaemon",
}

PB_UTIL.ENABLED_SPECTRALS = {
  "apostle_of_cups",
  "apostle_of_wands",
  "apostle_of_swords",
  "apostle_of_pentacles",
}

PB_UTIL.ENABLED_BLINDS = {
  "quarter",
  "half",
  "whole",
  "rest",
  "flat",
  "sharp",
  "natural",
  "coda",
  "hold",
  "glissando",
  -- "denim_da_capo",
  "misty_bass",
  "taupe_treble"
  -- "black_silence",
  -- "pearlescent_orchestra",
  -- "scarlet_score",

  -- "alphabet",
  -- "bellcurve",
  -- "claw",
  -- "door",
  -- "electric",
  -- "finger",
  -- "guild",
  -- "hunger",
  -- "index",
  -- "joker",
  -- "knight",
  -- "lingering",
  -- "mistake",
  -- "noxious",
  -- "origin",
  -- "painting",
  -- "quiz",
  -- "reaping",
  -- "sowing",
  -- "taboo",
  -- "unit",
  -- "vice",
  -- "wish",
  -- "x-ray",
  -- "year",
  -- "zealot",
}


PB_UTIL.ENABLED_VOUCHERS = {
  'celtic_cross',
  'soothsay',
  -- 'filing_cabinet',
  -- 'paperclip_optimization',
  'second_trumpet',
  'rabbit_protocol',
}

PB_UTIL.ENABLED_TAGS = {
  'angel_investment',
  'divination',
  'dichrome',
  'high_risk',
  'breaking',
}

PB_UTIL.ENABLED_ENHANCEMENTS = {
  "wrapped",
  "bandaged",
  "ceramic",
  "soaked",
  "stained",
  "domino",
  "sleeved",
  "antique"
}

PB_UTIL.ENABLED_EDITIONS = {
  'dichrome'
}

PB_UTIL.ENABLED_RANKS = {
  'apostle'
}

PB_UTIL.ENABLED_POKER_HANDS = {
  'spectrum',
  'straight_spectrum',
  'spectrum_house',
  'spectrum_five',
}

PB_UTIL.ENABLED_PLANETS = {
  'quaoar',
  'haumea',
  'sedna',
  'makemake',
}

PB_UTIL.ENABLED_DECKS = {
  'paper',
  'proud',
  'silver',
  'dreamer',
  'antique',
  'passionate',
  'shimmering',
}

PB_UTIL.ENABLED_CHALLENGES = {
  "trial_of_cups",
  "trial_of_wands",
  "trial_of_swords",
  "trial_of_pentacles",

  'hide_and_seek',
  'white_nights_and_dark_days',
  'suburbia_overture',
  'hard_cover',
  'borderline',
  'all_smiles',
  'joker_of_the_day',
  'foodie'
}

PB_UTIL.ENABLED_STICKERS = {
  'energized',
  'temporary',
  'corroded'
}

PB_UTIL.ENABLED_ATTRIBUTES = {
  'light',        -- trigger is affected by any light suit (hearts, diamonds, stars)
  'dark',         -- trigger is affected by any dark suit (spades, clubs, crowns)
  'stars',        -- trigger is affected by stars
  'crowns',       -- trigger is affected by crowns
  'apostle',      -- trigger is affected by apostles
  'rankless',     -- trigger is affected by rankless cards
  'paperclip',    -- related to paperclips
  'minor_arcana', -- related to minor arcana
  'ego_gift',     -- related to ego gifts
  'negative',     -- related to the negative edition
  'ante',         -- changes ante
  'music',        -- based on a song/album
  'secret',       -- has a secret trigger
  'red',          -- it's red
  'stick'         -- it's stick
}
